language: node_js
node_js:
  - "8"

services:
   - postgresql

cache:
directories:
  - "node_modules"


before_script:

  - psql -c 'create database travis_db;' -U postgres


script:
  - npm run test




