language: node_js
node_js:
  - stable
  - 8.9.4

services:
  - postgresql

cache:
directories:
  - "node_modules"


before_script:
  - psql -c 'create database travisdb;' -U postgres

install:
  - npm install
script:
  - npm run test
  - npm run coveralls




