language: node_js
node_js:
  - stable
  - 8.9.4

services:
  - postgresql

cache:
directories:
  - "node_modules"


before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

install:
  - npm install
script:
  - npm run test


after_script:
  - npm run coverage